#!/bin/bash

MY_NAME="pingsoli"
MY_HOME="/home/$MY_NAME"

SRC_VIM_CONF="$MY_HOME/.vimrc"
SRC_VIM_SNIPPETS_DIR="$MY_HOME/.vim/UltiSnips"
SRC_YCM_CONF="$MY_HOME/.vim/.ycm_extra_conf.py"

SRC_TMUX_CONF="$MY_HOME/.tmux.conf"
SRC_FISH_CONF_DIR="$MY_HOME/.config/fish"

DST_VIM_DIR="./vim"
DST_TMUX_DIR="./tmux"
DST_FISH_DIR="./fish"

create_if_nonexist()
{
  for dir in "$@"; do
   if [ ! -d "$dir" ]; then
     mkdir -p "$dir"
   fi
  done
}

backup_necessary_files()
{
  # Show all executing command
  set -x

  # Fish, '-L' follows symbolic link to copy real file
  cp -r -L "$SRC_FISH_CONF_DIR/"*  "$DST_FISH_DIR"

  # Tmux
  cp    "$SRC_TMUX_CONF"        "$DST_TMUX_DIR"

  # Vim
  cp    "$SRC_VIM_CONF"         "$DST_VIM_DIR"
  mkdir -p "$DST_VIM_DIR/.vim/UltiSnips" && \
  cp -r "$SRC_VIM_SNIPPETS_DIR/"* "$DST_VIM_DIR/.vim/UltiSnips"
  cp    "$SRC_YCM_CONF"           "$DST_VIM_DIR/.vim"

  # set +x not echo
  { set +x; } 2>/dev/null
}

backup()
{
  local wanted_dirs=($DST_VIM_DIR $DST_TMUX_DIR $DST_FISH_DIR)

  # Remove all backup
  for dir_name in ${wanted_dirs[@]}; do
     rm -rf "$dir_name" 2> /dev/null
  done

  # Create necessary folders
  for dir_name in ${wanted_dirs[@]}; do
    create_if_nonexist $dir_name
  done

  backup_necessary_files
}

push()
{
  git add .
  git commit -m "$1"
  git push origin master
}

recover()
{
  local wanted_dirs=($MY_HOME/.config $MY_HOME/.vim)
  for dir_name in ${wanted_dirs[@]}; do
    create_if_nonexist $dir_name
  done

  # Show all executing command
  set -x

  cp -u "./vim/.vimrc" "$MY_HOME"
  cp -ru "./vim/.vim" "$MY_HOME"
  cp -u "./tmux/.tmux.conf" "$MY_HOME"
  # Firstly, delete all symbolic links
  find "$MY_HOME/.config/fish" -type l -delete
  cp -ru "./fish" "$MY_HOME/.config"

  # set +x not echo
  { set +x; } 2>/dev/null
}

help()
{
  echo -e "\nUsage: "
  echo -e "  $0 [start|s]      \t backup all necessary dotfiles"
  echo -e "  $0 [push|p <msg>] \t backup and push to GitHub"
  echo -e "  $0 [recover|r]    \t restore dotfiles"
  echo -e "  $0 [help|h]       \t manual"
}

case "$1" in
  start|s)
    backup
    ;;

  push|p)
    backup

    if [ "$#" -ne 2 ]; then
      echo -e "no commit message\nusage: ./backup push <msg>"
      exit 1
    fi

    push "$2"
    ;;

  recover|r)
    recover
    ;;

  help|h)
    help
    ;;

  *)
    help
esac
